# Hyderabad House Prices Practice Notebook
Dataset + 30 NumPy & Pandas practice questions.

In [3]:

import pandas as pd
import numpy as np

df = pd.DataFrame({
'House_ID': np.arange(101,131),
'Location': ['Gachibowli','Madhapur','Kukatpally','Miyapur','Hitech City','Kondapur','Begumpet','Ameerpet','Manikonda','Banjara Hills','Jubilee Hills','LB Nagar','Uppal','Dilsukhnagar','Secunderabad','Gachibowli','Madhapur','Kukatpally','Miyapur','Hitech City','Kondapur','Begumpet','Ameerpet','Manikonda','Banjara Hills','Jubilee Hills','LB Nagar','Uppal','Dilsukhnagar','Secunderabad'],
'Type': ['Apartment','Villa','Apartment','Apartment','Villa','Apartment','Apartment','Apartment','Villa','Villa','Villa','Apartment','Apartment','Apartment','Apartment','Villa','Apartment','Apartment','Apartment','Villa','Apartment','Apartment','Apartment','Villa','Villa','Villa','Apartment','Apartment','Apartment','Apartment'],
'Bedrooms': [2,4,3,2,5,3,2,2,4,5,6,3,2,2,3,4,3,2,2,5,3,2,2,4,5,6,3,2,2,3],
'Bathrooms': [2,4,3,2,5,3,2,2,4,5,6,3,2,2,3,4,3,2,2,5,3,2,2,4,5,6,3,2,2,3],
'Area_Sqft': [1200,3200,1600,1100,4200,1700,1250,1150,2800,5000,6200,1500,1180,1120,1450,3500,1650,1300,1080,4300,1750,1280,1170,2900,5200,6400,1520,1210,1140,1480],
'Age_Years': [5,2,8,10,1,6,12,9,3,2,1,7,11,13,8,4,5,9,10,2,6,12,10,4,3,1,8,11,14,9],
'Parking': [1,2,1,1,3,1,1,1,2,3,4,1,1,1,1,2,1,1,1,3,1,1,1,2,3,4,1,1,1,1],
'Price_Lakhs': [75,280,95,68,420,110,82,78,240,650,850,98,72,70,105,310,102,80,66,430,115,84,79,250,670,880,100,74,69,108],
'Furnished': ['Semi','Full','Semi','Unfurnished','Full','Semi','Unfurnished','Semi','Full','Full','Full','Semi','Unfurnished','Unfurnished','Semi','Full','Semi','Semi','Unfurnished','Full','Semi','Unfurnished','Semi','Full','Full','Full','Semi','Unfurnished','Unfurnished','Semi']
})
df

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi

## 30 Practice Questions
1. First 5 rows
2. Last 5 rows
3. Shape
4. Columns
5. Data types
6. Houses where Price_Lakhs > 300
7. Villas only
8. Houses in Gachibowli
9. Apartments with 3 bedrooms
10. Houses older than 10 years
11. Sort by price ascending
12. Sort by area descending
13. Sort by age ascending
14. Create Price_per_Sqft
15. Create Luxury column (Price > 500)
16. Average price by Location
17. Max price by Type
18. Count houses by Furnished
19. Average area by Bedrooms
20. Total listings by Location and Type
21. Missing values each column
22. Fill missing Price_Lakhs with mean
23. Fill missing Furnished with mode
24. Convert Price_Lakhs to NumPy array
25. Max/min/mean price using NumPy
26. Std deviation of Area_Sqft
27. Houses with price > avg using NumPy
28. Reshape first 12 prices into 3x4
29. Top 5 costly houses
30. Correlation Area_Sqft vs Price_Lakhs

In [3]:
# Write your solutions here
df

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi

In [4]:
# first 5 rows
df.head()

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full

In [5]:
# last 5 rows
df.tail()

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi

In [8]:
# shape of table
df.shape

(30, 10)

In [9]:
# columns in a table
df.columns

Index(['House_ID', 'Location', 'Type', 'Bedrooms', 'Bathrooms', 'Area_Sqft',
       'Age_Years', 'Parking', 'Price_Lakhs', 'Furnished'],
      dtype='object')

In [10]:
# data types
df.dtypes

House_ID        int64
Location       object
Type           object
Bedrooms        int64
Bathrooms       int64
Area_Sqft       int64
Age_Years       int64
Parking         int64
Price_Lakhs     int64
Furnished      object
dtype: object

In [13]:
# 300 Lakhs more in house price
df[df['Price_Lakhs']>300]

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full

In [16]:
# Villas in different areas
df[df['Type']=='Villa']

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full

In [22]:
# Gochibowli location
df[df['Location']=='Gachibowli']

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full

In [35]:
# apartment and more than 3 Bedrooms
df[(df['Type']=='Apartment') & (df['Bedrooms']==3)]

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi

In [39]:
# age greter than 10 years in house 
df[df['Age_Years']>10]

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished

In [46]:
# House prices are ascending 
df.sort_values(by='Price_Lakhs')

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full

In [49]:
# Area are descending order
df.sort_values(by='Area_Sqft',ascending=False)

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished

In [53]:
# ages are descending order
df.sort_values(by='Age_Years',ascending=False)

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full

In [58]:
# add column Sqft_Per_Unit
df['Sqft_Per_Unit']=df['Price_Lakhs']/df['Area_Sqft']

In [59]:
df

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished,Sqft_Per_Unit
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi,0.062500
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full,0.087500
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi,0.059375
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished,0.061818
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full,0.100000
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi,0.064706
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished,0.065600
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi,0.067826
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full,0.085714
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full,0.130000
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full,0.137097
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi,0.065333
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished,0.061017
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished,0.062500
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi,0.072414
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full,0.088571
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi,0.061818
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi,0.061538
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished,0.061111
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full,0.100000
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi,0.065714
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished,0.065625
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi,0.067521
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full,0.086207
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full,0.128846
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full,0.137500
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi,0.065789
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished,0.061157
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished,0.060526
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi,0.072973

In [66]:
# add column Luxury are house price more than 500 lakhs
df['Luxury']=df['Price_Lakhs']>500
df

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished,Sqft_Per_Unit,Luxury
0,101,Gachibowli,Apartment,2,2,1200,5,1,75,Semi,0.062500,False
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full,0.087500,False
2,103,Kukatpally,Apartment,3,3,1600,8,1,95,Semi,0.059375,False
3,104,Miyapur,Apartment,2,2,1100,10,1,68,Unfurnished,0.061818,False
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full,0.100000,False
5,106,Kondapur,Apartment,3,3,1700,6,1,110,Semi,0.064706,False
6,107,Begumpet,Apartment,2,2,1250,12,1,82,Unfurnished,0.065600,False
7,108,Ameerpet,Apartment,2,2,1150,9,1,78,Semi,0.067826,False
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full,0.085714,False
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full,0.130000,True
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full,0.137097,True
11,112,LB Nagar,Apartment,3,3,1500,7,1,98,Semi,0.065333,False
12,113,Uppal,Apartment,2,2,1180,11,1,72,Unfurnished,0.061017,False
13,114,Dilsukhnagar,Apartment,2,2,1120,13,1,70,Unfurnished,0.062500,False
14,115,Secunderabad,Apartment,3,3,1450,8,1,105,Semi,0.072414,False
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full,0.088571,False
16,117,Madhapur,Apartment,3,3,1650,5,1,102,Semi,0.061818,False
17,118,Kukatpally,Apartment,2,2,1300,9,1,80,Semi,0.061538,False
18,119,Miyapur,Apartment,2,2,1080,10,1,66,Unfurnished,0.061111,False
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full,0.100000,False
20,121,Kondapur,Apartment,3,3,1750,6,1,115,Semi,0.065714,False
21,122,Begumpet,Apartment,2,2,1280,12,1,84,Unfurnished,0.065625,False
22,123,Ameerpet,Apartment,2,2,1170,10,1,79,Semi,0.067521,False
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full,0.086207,False
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full,0.128846,True
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full,0.137500,True
26,127,LB Nagar,Apartment,3,3,1520,8,1,100,Semi,0.065789,False
27,128,Uppal,Apartment,2,2,1210,11,1,74,Unfurnished,0.061157,False
28,129,Dilsukhnagar,Apartment,2,2,1140,14,1,69,Unfurnished,0.060526,False
29,130,Secunderabad,Apartment,3,3,1480,9,1,108,Semi,0.072973,False

In [67]:
# average of price in each location
df.groupby('Location')['Price_Lakhs'].mean()

Location
Ameerpet          78.5
Banjara Hills    660.0
Begumpet          83.0
Dilsukhnagar      69.5
Gachibowli       192.5
Hitech City      425.0
Jubilee Hills    865.0
Kondapur         112.5
Kukatpally        87.5
LB Nagar          99.0
Madhapur         191.0
Manikonda        245.0
Miyapur           67.0
Secunderabad     106.5
Uppal             73.0
Name: Price_Lakhs, dtype: float64

In [68]:
# Max price by type
df.groupby('Type')['Price_Lakhs'].max()

Type
Apartment    115
Villa        880
Name: Price_Lakhs, dtype: int64

In [81]:
# count houses by furnishedd
df['Furnished'].value_counts()

Furnished
Semi           12
Full           10
Unfurnished     8
Name: count, dtype: int64

In [83]:
# average area by bedrooms
df.groupby('Bedrooms')['Area_Sqft'].mean()

Bedrooms
2    1181.666667
3    1581.250000
4    3100.000000
5    4675.000000
6    6300.000000
Name: Area_Sqft, dtype: float64

In [85]:
# Total listings by location and type
df.groupby(['Location','Type']).size()

Location       Type
Ameerpet       Apartment    2
Banjara Hills  Villa        2
Begumpet       Apartment    2
Dilsukhnagar   Apartment    2
Gachibowli     Apartment    1
               Villa        1
Hitech City    Villa        2
Jubilee Hills  Villa        2
Kondapur       Apartment    2
Kukatpally     Apartment    2
LB Nagar       Apartment    2
Madhapur       Apartment    1
               Villa        1
Manikonda      Villa        2
Miyapur        Apartment    2
Secunderabad   Apartment    2
Uppal          Apartment    2
dtype: int64

In [94]:
# missing values in each column
df.isnull().sum()

House_ID         0
Location         0
Type             0
Bedrooms         0
Bathrooms        0
Area_Sqft        0
Age_Years        0
Parking          0
Price_Lakhs      0
Furnished        0
Sqft_Per_Unit    0
Luxury           0
dtype: int64

In [99]:
# 24) convert into price_lakhs into numpy array
price=df['Price_Lakhs'].to_numpy()

In [100]:
price

array([ 75, 280,  95,  68, 420, 110,  82,  78, 240, 650, 850,  98,  72,
        70, 105, 310, 102,  80,  66, 430, 115,  84,  79, 250, 670, 880,
       100,  74,  69, 108])

In [108]:
# 25) max,min , mean() usinng numpy
np.max(price)

np.int64(880)

In [109]:
np.min(price)

np.int64(66)

In [110]:
np.mean(price)

np.float64(223.66666666666666)

In [115]:
# 26) std deviation of area sqft
np.std(df['Area_Sqft'])

1606.149328881554

In [116]:
# 27) house with price > avg using numpy
avg=np.mean(price)
df[df['Price_Lakhs']>avg]

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished,Sqft_Per_Unit,Luxury
1,102,Madhapur,Villa,4,4,3200,2,2,280,Full,0.087500,False
4,105,Hitech City,Villa,5,5,4200,1,3,420,Full,0.100000,False
8,109,Manikonda,Villa,4,4,2800,3,2,240,Full,0.085714,False
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full,0.130000,True
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full,0.137097,True
15,116,Gachibowli,Villa,4,4,3500,4,2,310,Full,0.088571,False
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full,0.100000,False
23,124,Manikonda,Villa,4,4,2900,4,2,250,Full,0.086207,False
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full,0.128846,True
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full,0.137500,True

In [119]:
df['Price_Lakhs'].mean()

np.float64(223.66666666666666)

In [127]:
# 28) reshape of first 12 prices into 3X4
price[:12].reshape(3,4)

array([[ 75, 280,  95,  68],
       [420, 110,  82,  78],
       [240, 650, 850,  98]])

In [134]:
#29) costly 5 houses
df.sort_values(by='Price_Lakhs',ascending=False).head(5)

,House_ID,Location,Type,Bedrooms,Bathrooms,Area_Sqft,Age_Years,Parking,Price_Lakhs,Furnished,Sqft_Per_Unit,Luxury
25,126,Jubilee Hills,Villa,6,6,6400,1,4,880,Full,0.137500,True
10,111,Jubilee Hills,Villa,6,6,6200,1,4,850,Full,0.137097,True
24,125,Banjara Hills,Villa,5,5,5200,3,3,670,Full,0.128846,True
9,110,Banjara Hills,Villa,5,5,5000,2,3,650,Full,0.130000,True
19,120,Hitech City,Villa,5,5,4300,2,3,430,Full,0.100000,False

In [136]:
# correlation area_sqft vs Price_lakhs
df['Area_Sqft'].corr(df['Price_Lakhs'])

np.float64(0.9859508698365943)